sudo: false

language: d

install:
  - wget -O doveralls "https://github.com/ColdenCullen/doveralls/releases/download/v1.1.6/doveralls_linux_travis"
  - chmod +x doveralls

script:
  - dub test -b unittest-cov

after_success:
  - bash <(curl -s https://codecov.io/bash)
